/*
 * @Author: czy0729
 * @Date: 2022-09-13 21:03:42
 * @Last Modified by: czy0729
 * @Last Modified time: 2026-10-06 07:37:37
 */
import { ANIME_COLLECTED, ANIME_YEAR } from '../anime'

/** 年份筛选, 复用动画年份列表 */
export const GAME_YEAR = ANIME_YEAR

/** 收藏筛选, 复用动画 */
export const GAME_COLLECTED = ANIME_COLLECTED

/** 分级筛选 (「全部」由通用筛选组提供, 点击时写入空串) */
export const GAME_NSFW = ['限制', '未知'] as const

export const GAME_PLATFORM = [
  'PC',
  'NS',
  'PS5',
  'PS4',
  'XSX|S',
  'XB1',
  'PS3',
  'PS2',
  'PSV',
  'PSP',
  '3DS',
  'NDS',
  'X360',
  'iOS',
  'Android',
  'GBA',
  'Wii',
  'WiiU',
  'PS',
  'Xbox',
  'Stadia',
  'SFC',
  'FC',
  'GBC',
  'GB',
  'DC',
  'NGC',
  'Saturn',
  'N64',
  'MD',
  'Arcade'
] as const

/** 平台 → Item.pl 中的下标 */
const GAME_PLATFORM_MAP = {}
GAME_PLATFORM.forEach((item, index) => {
  GAME_PLATFORM_MAP[item] = index
})

export { GAME_PLATFORM_MAP }

/** 分类, 顺序即 GAME_CATE_MAP 的序号 */
export const GAME_CATE = [
  '动作',
  '角色扮演',
  '冒险',
  '射击',
  '策略',
  '第三人称',
  '独立',
  '文字',
  '模拟',
  '主视角',
  '剧情',
  '平台',
  '解谜',
  '多人',
  '恐怖',
  '格斗',
  '回合制',
  '科幻',
  '音乐',
  '育成',
  '益智',
  '生存',
  '体育',
  '沙箱',
  '开放世界',
  '竞速',
  '竞技',
  '即时战略',
  '俯视角',
  '卡牌',
  'MMO',
  '3D',
  '派对',
  '潜入',
  'Roguelike',
  'VR',
  '体感',
  '健身',
  '塔防',
  '建造',
  'MOBA',
  '弹幕',
  'AR',
  '桌面',
  '2D',
  '横版',
  '养成'
] as const

export const GAME_CATE_MAP = Object.fromEntries(
  GAME_CATE.map((item, index) => [item, index])
) as Record<(typeof GAME_CATE)[number], number>

/** 开发商, 顺序即 GAME_DEV_MAP 的序号 */
export const GAME_DEV = [
  'CAPCOM',
  'Nintendo',
  'KONAMI',
  'Bandai Namco',
  'Square Enix',
  'オトメイト',
  'SEGA',
  'Ubisoft',
  'Koei Tecmo',
  'カイロソフト',
  'ディーゼルマイン',
  'Design Factory',
  'スクウェア・エニックス',
  'Atlus',
  '日本一',
  'Team Ninja',
  'Nihon Falcom',
  'Game Freak',
  'Inc.',
  'Gust Co. Ltd.',
  'EA',
  'Omega Force',
  'QuinRose',
  '5pb.',
  'Marvelous',
  'Intelligent Systems',
  'アークシステムワークス',
  'Arc System Works',
  'LEVEL-5',
  'Rejet',
  'Telltale Games',
  'Sony Interactive Entertainment',
  'Ubisoft Montreal (Ubisoft Entertainment)',
  'Blizzard',
  '日本一ソフトウェア',
  'ガスト',
  'Ltd.',
  'ALICESOFT',
  '禁飼育',
  '上海アリス幻樂団',
  'MAGES.',
  'ILLUSION(Dreams)',
  'SNK',
  'Valve',
  'BioWare',
  'Kojima Productions',
  'Spike Chunsoft',
  'ImCyan (アイムシアン)',
  '大宇資訊',
  'FromSoftware',
  'コーエーテクモホールディングス',
  'Compile Heart',
  'コンパイルハート',
  'Visual Concepts',
  'Codemasters',
  'id Software',
  'WAFFLE',
  'エロフラ部',
  'Rockstar Games',
  'Naughty Dog',
  'Bungie',
  'エルフ',
  'KID',
  'tri-Ace',
  'ω-force',
  'CyberConnect2',
  'Creative Assembly',
  'CD PROJEKT RED',
  'Cygames',
  'LoyaltyGame B.V.',
  'Rusty Lake',
  'Vaka Game Magazine',
  'Polyphony Digital',
  'Sports Interactive',
  'バンダイナムコエンターテインメント(バンダイナムコゲームス)',
  'Treyarch',
  'ゲームフリーク',
  'AQUAPLUS',
  'PlatinumGames',
  'アトラス',
  '戯画',
  'アクトレス',
  'SEEC inc.',
  'West Vision',
  'Nitrome',
  'Square',
  'レベルファイブ',
  'Monolith Soft',
  'DICE',
  'Bethesda',
  '弘煜科技',
  'JAPAN Studio',
  '日本ファルコム',
  '株式会社ブリッジ',
  'Acquire',
  'Blizzard Entertainment',
  'DOMO Studio',
  'コーエー',
  'Firaxis Games',
  '株式会社レッド・エンタテインメント',
  '美蕾',
  'Kadokawa Games',
  'TAKUYO',
  'Ubisoft Montpellier (Ubisoft Entertainment)',
  'Tamsoft',
  'Saber Interactive',
  'Guilty',
  'ANIM',
  'U･Me SOFT',
  "Chilla's Art",
  '毒電波新聞社',
  'たんち',
  'Infinity Ward',
  'Type-Moon',
  'フロム・ソフトウェア',
  'Artdink',
  'スパイク・チュンソフト',
  'エンターブレイン',
  'Playground Games',
  'KONAMI開発1課',
  'Otomate',
  'softhouse-seal',
  'マーベラス',
  '黒雛',
  'BLACK PACKAGE TRY',
  'Epic Games',
  'BANPRESTO',
  'HAL Laboratory',
  'Inti Creates',
  'Obsidian Entertainment',
  'Vanillaware',
  'Gearbox Software',
  'Nixxes Software(PC)',
  'Rebellion',
  'Crystal Dynamics',
  'ZyX',
  'プラチナゲームズ',
  '任天堂企画制作本部',
  'フェアリーテール',
  'Triangle',
  'Supermassive Games',
  'ブルーゲイル',
  'なぎや本舗',
  '米哈游',
  'Insomniac Games',
  'EA Canada (Electronic Arts)',
  'Chunsoft',
  'インティ・クリエイツ',
  'IO Interactive',
  'Beenox',
  'インテリジェントシステムズ',
  'WayForward',
  'Alfa System',
  'Namco',
  '花梨エンターテイメント',
  'Amanita Design',
  'Sumo Digital',
  'New World Computing',
  'Red Entertainment',
  'Santa Monica Studio'
] as const

export const GAME_DEV_MAP = Object.fromEntries(
  GAME_DEV.map((item, index) => [item, index])
) as Record<(typeof GAME_DEV)[number], number>

/** 数据侧清洗残留的公司后缀, 不参与筛选展示 */
export const GAME_JUNK: string[] = ['Inc.', 'Ltd.', 'Android)']

/** 同一开发商的不同写法, 筛选时同组成员互相命中 */
export const GAME_DEV_ALIAS = [
  ['Nintendo', '任天堂企画制作本部'],
  ['Square Enix', 'スクウェア・エニックス'],
  ['Koei Tecmo', 'コーエーテクモホールディングス', 'コーエー'],
  ['Bandai Namco', 'バンダイナムコエンターテインメント(バンダイナムコゲームス)'],
  ['Atlus', 'アトラス'],
  ['Nihon Falcom', '日本ファルコム'],
  ['Game Freak', 'ゲームフリーク'],
  ['Gust Co. Ltd.', 'ガスト'],
  ['Marvelous', 'マーベラス'],
  ['Intelligent Systems', 'インテリジェントシステムズ'],
  ['Arc System Works', 'アークシステムワークス'],
  ['LEVEL-5', 'レベルファイブ'],
  ['Blizzard', 'Blizzard Entertainment'],
  ['KONAMI', 'KONAMI開発1課'],
  ['日本一', '日本一ソフトウェア'],
  ['Omega Force', 'ω-force'],
  ['5pb.', 'MAGES.'],
  ['PlatinumGames', 'プラチナゲームズ'],
  ['Compile Heart', 'コンパイルハート'],
  ['FromSoftware', 'フロム・ソフトウェア'],
  ['Spike Chunsoft', 'スパイク・チュンソフト', 'Chunsoft'],
  ['オトメイト', 'Otomate'],
  ['Inti Creates', 'インティ・クリエイツ'],
  ['Red Entertainment', '株式会社レッド・エンタテインメント'],
  [
    'Ubisoft',
    'Ubisoft Montreal (Ubisoft Entertainment)',
    'Ubisoft Montpellier (Ubisoft Entertainment)'
  ]
] as const

/** 发行商, 顺序即 GAME_PUB_MAP 的序号 */
export const GAME_PUB = [
  'Nintendo',
  'SEGA',
  'Bandai Namco',
  'Square Enix',
  'Konami',
  'CAPCOM',
  'Sony Interactive Entertainment',
  'Koei Tecmo',
  '任天堂',
  'アイディアファクトリー株式会社',
  'EA',
  'Ubisoft',
  'スクウェア・エニックス',
  'Electronic Arts',
  '腾讯游戏',
  'Activision',
  'Devolver Digital',
  'Microsoft',
  'Ubisoft Entertainment',
  'Kagura Games',
  'Atlus',
  '网易游戏',
  'PLAYISM',
  'Marvelous',
  '5pb.',
  '2K Games',
  'Ltd.',
  '寰宇之星',
  'Paradox Interactive',
  '505 Games',
  'ディースリー・パブリッシャー',
  '日本一',
  'カイロソフト',
  '大宇資訊',
  '2K',
  'バンダイナムコエンターテインメント',
  'Bethesda Softworks',
  'Inc.',
  'Kadokawa Games',
  'MAGES.',
  'THQ Nordic',
  'Deep Silver',
  'Nihon Falcom',
  'The Pokémon Company',
  'Bethesda',
  'Warner Bros. Games',
  '哔哩哔哩游戏',
  'Annapurna Interactive',
  'QuinRose',
  'Xbox Game Studios',
  'Raw Fury',
  '大宇资讯',
  'アイチェリー',
  'Arc System Works',
  'コーエーテクモゲームス',
  '電脳CLUB',
  'Focus Home Interactive',
  'tinyBuild',
  'N43 Project',
  'OTAKU Plan',
  'Mango Party',
  '智冠科技',
  'マーベラス',
  '雷霆游戏',
  'Team17',
  'Microsoft Studios',
  'Compile Heart',
  'TAITO',
  'Telltale Games',
  'LEVEL-5',
  '心动网络',
  'Rockstar Games',
  'Dramatic Create',
  'DMM GAMES（合同会社EXNOA）',
  'indienova',
  'Gamera Games',
  'SNK',
  'Valve',
  'バンダイナムコゲームス',
  'アークシステムワークス',
  'Nexon',
  'オトメイト',
  '东方明珠（中国大陆）',
  'Blizzard Entertainment',
  'NBGI',
  'コーエーテクモホールディングス',
  'Kalypso Media',
  'Daedalic Entertainment',
  'BANPRESTO',
  'Spike Chunsoft',
  '日本一ソフトウェア',
  '日本ファルコム',
  'Idea Factory',
  'Humble Games',
  'KID',
  '光譜資訊(繁体中文版)',
  'コーエー',
  'D3 Publisher',
  '东品游戏（Android）',
  '禁飼育',
  '072 Project',
  '方块游戏',
  'Blizzard',
  'NAMCO',
  '角川ゲームス',
  'AQUAPLUS',
  'Rejet',
  'Android)',
  'agony',
  'Eidos Interactive',
  'サイバーフロント',
  '株式会社プロトタイプ',
  'Softhouse-Seal',
  'Rusty Lake',
  'Nacon',
  'Prototype',
  'Square',
  'Codemasters',
  'THQ',
  'フロム・ソフトウェア(日本)',
  'TAKUYO',
  'Cygames',
  'Curve Games',
  'HypeTrain Digital',
  'Hooded Horse',
  'Vaka Game Magazine',
  'IndieArk',
  'レベルファイブ',
  'サクセス(SuperLite2000)',
  'Warner Bros. Interactive Entertainment',
  '株式会社ポケモン',
  'XSEED Games',
  'スパイク・チュンソフト',
  '3DO',
  'Degica',
  '美蕾',
  'F&C Co.',
  'Hina Soft',
  'アイディアファクトリー',
  'elf',
  '11 bit studios',
  'PlayWay S.A.',
  'Waffle',
  'ウェストビジョン',
  'Gamera Game',
  "Chilla's Art",
  '2P Games',
  'Sekai Project',
  'Feral Interactive (Mac)',
  'SCE',
  'テクモ',
  '中电博亚',
  'Sierra Entertainment',
  'アトラス',
  'Alicesoft',
  'WASABI entertainment',
  'DANGEN Entertainment',
  'ImCyan (アイムシアン)',
  'U･Me SOFT',
  'Akupara Games'
] as const

export const GAME_PUB_MAP = Object.fromEntries(
  GAME_PUB.map((item, index) => [item, index])
) as Record<(typeof GAME_PUB)[number], number>

/** 同一发行商的不同写法, 筛选时同组成员互相命中 */
export const GAME_PUB_ALIAS = [
  ['Nintendo', '任天堂'],
  ['Square Enix', 'スクウェア・エニックス'],
  ['EA', 'Electronic Arts'],
  ['Ubisoft', 'Ubisoft Entertainment'],
  ['Bethesda', 'Bethesda Softworks'],
  ['2K', '2K Games'],
  ['Microsoft', 'Microsoft Studios', 'Xbox Game Studios'],
  ['Bandai Namco', 'バンダイナムコエンターテインメント', 'バンダイナムコゲームス', 'NBGI'],
  ['Kadokawa Games', '角川ゲームス'],
  ['Idea Factory', 'アイディアファクトリー株式会社'],
  ['Koei Tecmo', 'コーエーテクモゲームス', 'コーエー'],
  ['Nihon Falcom', '日本ファルコム'],
  ['Marvelous', 'マーベラス'],
  ['Blizzard', 'Blizzard Entertainment'],
  ['D3 Publisher', 'ディースリー・パブリッシャー'],
  ['大宇資訊', '大宇资讯'],
  ['日本一', '日本一ソフトウェア'],
  ['Gamera Games', 'Gamera Game']
] as const

/** 排序, 顺序与标签同找番剧 (发行时间对应番剧的上映时间) */
export const GAME_SORT = ['排名', '发行时间', '评分人数', '随机'] as const

/**
 * 标签筛选 (全量 type=4 条目出现次数 top100, 下标即 bin 的 tg)
 *  - 已剔除年份标签, 同义标签 (大小写 / 繁简 / 日文新字体) 自动合并
 *  - 与 web/standalone/game 的 rule.loadTags 同步维护, 重建后如有变化需同步此表
 */
export const GAME_TAGS = [
  'ADV',
  'Galgame',
  'RPG',
  '拔作',
  'R18',
  '同人',
  '乙女',
  'ACT',
  '国产',
  '全年龄',
  'SLG',
  '黄油',
  '手游',
  'SIM',
  '合集',
  '汉化',
  'BL',
  '解谜',
  '独立游戏',
  'PUZ',
  '恐怖',
  'VN',
  'RPGMaker',
  'ARPG',
  '纯爱',
  '短篇',
  '萝莉',
  'DJ',
  '百合',
  'NTR',
  'STG',
  '生肉',
  'FPS',
  '后宫',
  '童年',
  '休闲',
  '动态CG',
  '巨乳',
  'FTG',
  '悬疑',
  'MUG',
  '日本',
  '妹',
  'JRPG',
  '凌辱',
  'HRPG',
  '人妻',
  '冒险',
  'SRPG',
  'Roguelike',
  '游戏性',
  '3D',
  '像素',
  'FD',
  'AAVG',
  'TPS',
  '调教',
  '猎奇',
  '废萌',
  '推理',
  'DLC',
  'RTS',
  'Linux',
  '扩展包',
  'ERO-RPG',
  'ARC',
  'SPG',
  'Capcom',
  'Mobile',
  'RAC',
  '幼驯染',
  '卡牌',
  '桌游',
  '科幻',
  'PC98',
  'MMORPG',
  'SEGA',
  '多人',
  '欧美',
  '网游',
  '恋爱',
  '普通游戏',
  'Konami',
  '横版',
  '经典',
  '视频通关',
  '策略',
  'ERO-ADV',
  '模拟经营',
  '韩国',
  '触手',
  '东方',
  'EPIC',
  'freegame',
  '实用',
  'DOS',
  'VR',
  'CG',
  '小游戏',
  'SS'
] as const
