/*
 * @Author: czy0729
 * @Date: 2023-04-05 01:43:31
 * @Last Modified by: czy0729
 * @Last Modified time: 2023-04-05 01:49:07
 */
export const list = [
  {
    id: '376137',
    name: '異世界のんびり農家',
    nameCn: '异世界悠闲农家',
    tip: '12话 / 2023年1月6日 / 倉谷涼一 / 内藤騎之介「異世界のんびり農家」 / (主)齊藤佳子、(副)五十内裕輔',
    rank: '',
    score: '7',
    simpleStars: true,
    tags: '2023年1月 异世界 轻小说改',
    comments: '',
    time: '2023-3-26',
    userCollection: '看过',
    cover: '//lain.bgm.tv/pic/cover/c/09/1a/376137_OjCOB.jpg',
    type: '动画',
    showLabel: false,
    isDo: false,
    isOnHold: false,
    isDropped: false,
    event: { id: '我的.跳转', type: 'list' },
    filter: ''
  },
  {
    id: '339326',
    name: '異世界おじさん',
    nameCn: '异世界舅舅',
    tip: '13话 / 2022年7月6日 / 河合滋樹 / 殆ど死んでいる(WebComicアパンダ連載/KADOKAWA刊) / 大田和寛',
    rank: '',
    score: '8',
    simpleStars: true,
    tags: '2022年7月 漫画改 异世界',
    comments: '',
    time: '2023-3-9',
    userCollection: '看过',
    cover: '//lain.bgm.tv/pic/cover/c/1a/75/339326_v466V.jpg',
    type: '动画',
    showLabel: false,
    isDo: false,
    isOnHold: false,
    isDropped: false,
    event: { id: '我的.跳转', type: 'list' },
    filter: ''
  },
  {
    id: '77476',
    name: 'シドニアの騎士',
    nameCn: '希德尼娅的骑士',
    tip: '12话 / 2014年4月10日',
    rank: '',
    score: '8',
    simpleStars: true,
    tags: '2014年4月 漫画改',
    comments: '',
    time: '2023-3-7',
    userCollection: '看过',
    cover: '//lain.bgm.tv/pic/cover/c/57/23/77476_tv6F8.jpg',
    type: '动画',
    showLabel: false,
    isDo: false,
    isOnHold: false,
    isDropped: false,
    event: { id: '我的.跳转', type: 'list' },
    filter: ''
  },
  {
    id: '163046',
    name: '迷家-マヨイガ-',
    nameCn: '迷家',
    tip: '12话 / 2016年4月1日 / 水島努 / diomedéa・ポニーキャニオン / 井出直美',
    rank: '',
    score: '1',
    simpleStars: true,
    tags: '2016年4月 原创 冈田麿里',
    comments: '补标，这么弱智的番（个人心中最弱智）是不可能看第二次的',
    time: '2023-2-14',
    userCollection: '看过',
    cover: '//lain.bgm.tv/pic/cover/c/c0/fc/163046_YU34C.jpg',
    type: '动画',
    showLabel: false,
    isDo: false,
    isOnHold: false,
    isDropped: false,
    event: { id: '我的.跳转', type: 'list' },
    filter: ''
  },
  {
    id: '391706',
    name: '機動戦士ガンダム 水星の魔女 PROLOGUE',
    nameCn: '机动战士高达 水星的魔女 PROLOGUE',
    tip: '1话 / 2022-07-14（先行）2022-09-25',
    rank: '',
    score: '9',
    simpleStars: true,
    tags: '',
    comments: '预算拉满',
    time: '2022-10-17',
    userCollection: '看过',
    cover: '//lain.bgm.tv/pic/cover/c/2a/9c/391706_GzNG2.jpg',
    type: '动画',
    showLabel: false,
    isDo: false,
    isOnHold: false,
    isDropped: false,
    event: { id: '我的.跳转', type: 'list' },
    filter: ''
  },
  {
    id: '342200',
    name: '異世界薬局',
    nameCn: '异世界药局',
    tip: '12话 / 2022年7月10日 / 草川啓造 / 高山理図（MFブックス／KADOKAWA刊） / 松本麻友子；副人物设定：前田恭佑',
    rank: '',
    score: '7',
    simpleStars: true,
    tags: '2022年7月 异世界 轻小说改',
    comments: '',
    time: '2022-9-28',
    userCollection: '看过',
    cover: '//lain.bgm.tv/pic/cover/c/05/43/342200_2hdHa.jpg',
    type: '动画',
    showLabel: false,
    isDo: false,
    isOnHold: false,
    isDropped: false,
    event: { id: '我的.跳转', type: 'list' },
    filter: ''
  },
  {
    id: '100403',
    name: '冴えない彼女の育てかた',
    nameCn: '路人女主的养成方法',
    tip: '13话 / 2015年1月8日 / 亀井幹太 / 丸戸史明（ファンタジア文庫／株式会社KADOKAWA 富士見書房BC） / 高瀬智章',
    rank: '',
    score: '',
    simpleStars: true,
    tags: '2015年1月 轻小说改',
    comments: '',
    time: '2022-9-4',
    userCollection: '看过',
    cover: '//lain.bgm.tv/pic/cover/c/6b/01/100403_JFsXn.jpg',
    type: '动画',
    showLabel: false,
    isDo: false,
    isOnHold: false,
    isDropped: false,
    event: { id: '我的.跳转', type: 'list' },
    filter: ''
  },
  {
    id: '331752',
    name: '進撃の巨人 The Final Season Part.2',
    nameCn: '进击的巨人 最终季 Part.2',
    tip: '12话 / 2022年1月9日 / 林祐一郎 / 諫山創（別冊少年マガジン連載／講談社） / 岸友洋',
    rank: '',
    score: '',
    simpleStars: true,
    tags: '2022年1月',
    comments: '',
    time: '2022-7-15',
    userCollection: '看过',
    cover: '//lain.bgm.tv/pic/cover/c/61/0c/331752_iRPHK.jpg',
    type: '动画',
    showLabel: false,
    isDo: false,
    isOnHold: false,
    isDropped: false,
    event: { id: '我的.跳转', type: 'list' },
    filter: ''
  },
  {
    id: '330055',
    name: '史上最強の大魔王、村人Aに転生する',
    nameCn: '史上最强的大魔王转生为村人A',
    tip: '12话 / 2022年4月6日 / 湊未來 / 下等妙人（株式会社KADOKAWA／ファンタジア文庫刊） / 野口孝行、[副人物设定]渡邊義弘（フロンティアワン）',
    rank: '',
    score: '5',
    simpleStars: true,
    tags: '2022年4月 轻小说改',
    comments: '真厕纸',
    time: '2022-7-4',
    userCollection: '看过',
    cover: '//lain.bgm.tv/pic/cover/c/22/3c/330055_AHxG5.jpg',
    type: '动画',
    showLabel: false,
    isDo: false,
    isOnHold: false,
    isDropped: false,
    event: { id: '我的.跳转', type: 'list' },
    filter: ''
  },
  {
    id: '356756',
    name: 'パリピ孔明',
    nameCn: '派对浪客诸葛孔明',
    tip: '12话 / 2022年4月5日 / 本間修 / 四葉夕卜・小川亮 （講談社「ヤングマガジン」連載） / 関口可奈味',
    rank: '',
    score: '8',
    simpleStars: true,
    tags: '2022年4月 P.A.WORKS 漫画改',
    comments: '',
    time: '2022-6-21',
    userCollection: '看过',
    cover: '//lain.bgm.tv/pic/cover/c/93/98/356756_ro03P.jpg',
    type: '动画',
    showLabel: false,
    isDo: false,
    isOnHold: false,
    isDropped: false,
    event: { id: '我的.跳转', type: 'list' },
    filter: ''
  },
  {
    id: '1905',
    name: 'サマーウォーズ',
    nameCn: '夏日大作战',
    tip: '1话 / 2009年8月1日 / 細田守 / 細田守 / 貞本義行',
    rank: '',
    score: '8',
    simpleStars: true,
    tags: '2009 剧场版 细田守',
    comments: '10多年后二刷, 也太好看了',
    time: '2022-6-7',
    userCollection: '看过',
    cover: '//lain.bgm.tv/pic/cover/c/73/e0/1905_5tj44.jpg',
    type: '动画',
    showLabel: false,
    isDo: false,
    isOnHold: false,
    isDropped: false,
    event: { id: '我的.跳转', type: 'list' },
    filter: ''
  },
  {
    id: '326870',
    name: '失格紋の最強賢者',
    nameCn: '失格纹的最强贤者',
    tip: '12话 / 2022年1月8日 / 秋田谷典昭 / 進行諸島 / 大沢美奈',
    rank: '',
    score: '6',
    simpleStars: true,
    tags: '',
    comments: '',
    time: '2022-4-27',
    userCollection: '看过',
    cover: '//lain.bgm.tv/pic/cover/c/62/b8/326870_NN377.jpg',
    type: '动画',
    showLabel: false,
    isDo: false,
    isOnHold: false,
    isDropped: false,
    event: { id: '我的.跳转', type: 'list' },
    filter: ''
  }
] as const
