/*
 * @Author: czy0729
 * @Date: 2022-05-11 04:37:23
 * @Last Modified by: czy0729
 * @Last Modified time: 2024-11-04 15:45:57
 */

/** Discovery */
export default {
  Anime: 'Anime',
  'Anime.跳转': 'Anime.to',
  'Anime.选择': 'Anime.onSelect',
  'Anime.到顶': 'Anime.scrollToTop',
  'Anime.切换布局': 'Anime.switchLayout',
  'Anime.更多': 'Anime.onPage',

  Anitama: 'Anitama',
  'Anitama.跳转': 'Anitama.to',
  'Anitama.右上角菜单': 'Anitama.topRightMenu',
  'Anitama.上一页': 'Anitama.prev',
  'Anitama.下一页': 'Anitama.next',
  'Anitama.页码跳转': 'Anitama.doSearch',
  'Anitama.切换站点': 'Anitama.toggleType',
  'Anitama.内置浏览器': 'Anitama.toggleUseWebView',

  Dollars: 'Dollars',
  'Dollars.跳转': 'Dollars.to',
  'Dollars.发送': 'Dollars.onSubmit',

  年鉴: 'Award',
  '年鉴.跳转': 'Award.to',
  '年鉴.错误': 'Award.error',
  '年鉴.浏览器打开': 'Award.browser',
  'Bangumi年鉴.跳转': 'Yearbook.to',

  索引: 'Browser',
  '索引.跳转': 'Browser.to',
  '索引.右上角菜单': 'Browser.topRightMenu',
  '索引.类型选择': 'Browser.onSelect',
  '索引.排序选择': 'Browser.onOrderSelect',
  '索引.年选择': 'Browser.onAirdateSelect',
  '索引.月选择': 'Browser.onMonthSelect',
  '索引.前一月': 'Browser.onAirdatePrev',
  '索引.后一月': 'Browser.onAirdateNext',
  '索引.切换布局': 'Browser.switchLayout',
  '索引.更多': 'Browser.onPage',

  每日放送: 'Calendar',
  '每日放送.跳转': 'Calendar.to',
  '每日放送.右上角菜单': 'Calendar.topRightMenu',
  '每日放送.切换布局': 'Calendar.switchLayout',
  '每日放送.切换类型': 'Calendar.onToggleType',
  '每日放送.切换改编': 'Calendar.onAdapt',
  '每日放送.切换标签': 'Calendar.onTag',
  '每日放送.切换动画制作': 'Calendar.onOrigin',

  目录: 'Catalog',
  '目录.跳转': 'Catalog.to',
  '目录.切换类型': 'Catalog.toggleType',
  '目录.上一页': 'Catalog.prev',
  '目录.下一页': 'Catalog.next',
  '目录.页码跳转': 'Catalog.doSearch',
  '目录.高级筛选': 'Catalog.onFilterChange',
  '目录.切换锁定': 'Catalog.onToggleFixed',
  '目录.右上角菜单': 'Catalog.topRightMenu',

  目录详情: 'CatalogDetail',
  '目录详情.跳转': 'CatalogDetail.to',
  '目录详情.右上角菜单': 'CatalogDetail.topRightMenu',
  '目录详情.收藏': 'CatalogDetail.doCollect',
  '目录详情.取消收藏': 'CatalogDetail.doErase',
  '目录详情.封面图查看': 'CatalogDetail.imageView',
  '目录详情.排序': 'CatalogDetail.sort',
  '目录详情.收藏范围': 'CatalogDetail.collect',
  '目录详情.管理': 'CatalogDetail.manage',
  '目录详情.复制': 'CatalogDetail.doCopy',
  '目录详情.切换布局': 'CatalogDetail.switchLayout',

  收藏的人物: 'Character',
  '收藏的人物.跳转': 'Character.to',
  '收藏的人物.右上角菜单': 'Character.topRightMenu',
  '收藏的人物.标签页切换': 'Character.tabsChange',

  发现: 'Discovery',
  '发现.跳转': 'Discovery.to',
  '发现.剪贴板': 'Discovery.linkModal',
  '发现.更新菜单': 'Discovery.saveMenus',
  '发现.下拉刷新': 'Discovery.onHeaderRefresh',
  '发现.滑动到边': 'Discovery.onEndReached',

  随便看看: 'Random',
  '随便看看.跳转': 'Random.to',

  排行榜: 'Rank',
  '排行榜.跳转': 'Rank.to',
  '排行榜.右上角菜单': 'Rank.topRightMenu',
  '排行榜.排序选择': 'Rank.onSortSelect',
  '排行榜.类型选择': 'Rank.onTypeSelect',
  '排行榜.筛选选择': 'Rank.onFilterSelect',
  '排行榜.二级分类选择': 'Rank.onFilterSubSelect',
  '排行榜.年选择': 'Rank.onAirdateSelect',
  '排行榜.月选择': 'Rank.onMonthSelect',
  '排行榜.来源选择': 'Rank.onSourceSelect',
  '排行榜.公共标签选择': 'Rank.onTagSelect',
  '排行榜.地区选择': 'Rank.onAreaSelect',
  '排行榜.受众选择': 'Rank.onTargetSelect',
  '排行榜.分级选择': 'Rank.onClassificationSelect',
  '排行榜.题材选择': 'Rank.onThemeSelect',
  '排行榜.工具栏': 'Rank.onToggleToolbar',
  '排行榜.切换布局': 'Rank.toggleList',
  '排行榜.上一页': 'Rank.prev',
  '排行榜.下一页': 'Rank.next',
  '排行榜.页码跳转': 'Rank.doSearch',

  搜索: 'Search',
  '搜索.跳转': 'Search.to',
  '搜索.右上角菜单': 'Search.topRightMenu',
  '搜索.切换类型': 'Search.onSelect',
  '搜索.选择历史': 'Search.selectHistory',
  '搜索.删除历史': 'Search.deleteHistory',
  '搜索.搜索': 'Search.doSearch',
  '搜索.切换细分类型': 'Search.onLegacySelect',
  '搜索.模糊查询点击': 'Search.onAdvance',
  '搜索.模糊查询跳转': 'Search.advanceTo',
  '搜索.条目直达': 'Search.navigate',
  '搜索.人物直达': 'Search.navigateMono',

  标签索引: 'Tags',
  '标签索引.跳转': 'Tags.to',
  '标签索引.右上角菜单': 'Tags.topRightMenu',
  '标签索引.标签页切换': 'Tags.tabsChange',
  '标签索引.标签类型切换': 'Tags.valueChange',
  '标签索引.筛选': 'Tags.submitEditing',

  全站日志: 'DiscoveryBlog',
  '全站日志.跳转': 'DiscoveryBlog.to',
  '全站日志.右上角菜单': 'DiscoveryBlog.topRightMenu',
  '全站日志.标签页切换': 'DiscoveryBlog.tabsChange',
  '全站日志.标签页点击': 'DiscoveryBlog.tabsPress',
  '全站日志.上一页': 'DiscoveryBlog.prev',
  '全站日志.下一页': 'DiscoveryBlog.next',
  '全站日志.页码跳转': 'DiscoveryBlog.doSearch',

  频道: 'Channel',
  '频道.跳转': 'Channel.to',
  '频道.右上角菜单': 'Channel.topRightMenu',

  文库: 'Wenku',
  '文库.跳转': 'Wenku.to',
  '文库.选择': 'Wenku.onSelect',
  '文库.到顶': 'Wenku.scrollToTop',
  '文库.切换布局': 'Wenku.switchLayout',
  '文库.更多': 'Wenku.onPage',

  Manga: 'Manga',
  'Manga.跳转': 'Manga.to',
  'Manga.选择': 'Manga.onSelect',
  'Manga.到顶': 'Manga.scrollToTop',
  'Manga.切换布局': 'Manga.switchLayout',
  'Manga.更多': 'Manga.onPage',

  游戏: 'Game',
  '游戏.跳转': 'Game.to',
  '游戏.选择': 'Game.onSelect',
  '游戏.到顶': 'Game.scrollToTop',
  '游戏.切换布局': 'Game.switchLayout',
  '游戏.更多': 'Game.onPage',

  ADV: 'ADV',
  'ADV.跳转': 'ADV.to',
  'ADV.选择': 'ADV.onSelect',
  'ADV.到顶': 'ADV.scrollToTop',
  'ADV.切换布局': 'ADV.switchLayout',
  'ADV.更多': 'ADV.onPage',

  推荐: 'Guess',
  '推荐.跳转': 'Guess.to',
  '推荐.刷新': 'Guess.refresh',

  新番档期: 'Staff',
  '新番档期.跳转': 'Staff.to',
  '新番档期.右上角菜单': 'Staff.topRightMenu',

  Hentai: 'Hentai',
  'Hentai.跳转': 'Hentai.to',
  'Hentai.选择': 'Hentai.onSelect',
  'Hentai.到顶': 'Hentai.scrollToTop',
  'Hentai.切换布局': 'Hentai.switchLayout',
  'Hentai.更多': 'Hentai.onPage',

  NSFW: 'NSFW',
  'NSFW.跳转': 'NSFW.to',
  'NSFW.选择': 'NSFW.onSelect',
  'NSFW.到顶': 'NSFW.scrollToTop',
  'NSFW.切换布局': 'NSFW.switchLayout',
  'NSFW.更多': 'NSFW.onPage',

  维基人: 'Wiki',
  '维基人.右上角菜单': 'Wiki.topRightMenu',

  猜你喜欢: 'Like',
  '猜你喜欢.跳转': 'Like.to',
  '猜你喜欢.切换': 'Like.switch',

  评分月刊: 'VIB',
  '评分月刊.跳转': 'VIB.to',
  '评分月刊.缩略框': 'VIB.popable',
  '评分月刊.上一期': 'VIB.prev',
  '评分月刊.下一期': 'VIB.next',
  '评分月刊.选择': 'VIB.select',

  半月刊: 'BiWeekly',
  '半月刊.右上角菜单': 'BiWeekly.topRightMenu',
  '半月刊.跳转': 'BiWeekly.to',

  词云: 'WordCloud',
  '词云.刷新': 'WordCloud.batch',
  '词云.分词': 'WordCloud.cut',
  '词云.点击': 'WordCloud.press',
  '词云.跳转': 'WordCloud.to'
}
