/*
 * @Author: czy0729
 * @Date: 2026-08-21 00:00:00
 * @Last Modified by: czy0729
 * @Last Modified time: 2026-08-21 00:00:00
 */

/**
 * BGM 原生表情资源映射（键为索引，值为打包后的资源模块 id）
 * 受 Metro 静态分析限制，require 必须逐条显式书写，无法用循环生成
 *
 * 注意：此处条目数量（102）需与 web 端 utils.ts 的 BGM_COUNT 保持一致，增减表情时两处同步修改
 */
export function getBgmAssets(): Record<number, number> {
  return {
    1: require('@bgm/01.gif') as number,
    2: require('@bgm/02.gif') as number,
    3: require('@bgm/03.gif') as number,
    4: require('@bgm/04.gif') as number,
    5: require('@bgm/05.gif') as number,
    6: require('@bgm/06.gif') as number,
    7: require('@bgm/07.gif') as number,
    8: require('@bgm/08.gif') as number,
    9: require('@bgm/09.gif') as number,
    10: require('@bgm/10.gif') as number,
    11: require('@bgm/11.gif') as number,
    12: require('@bgm/12.gif') as number,
    13: require('@bgm/13.gif') as number,
    14: require('@bgm/14.gif') as number,
    15: require('@bgm/15.gif') as number,
    16: require('@bgm/16.gif') as number,
    17: require('@bgm/17.gif') as number,
    18: require('@bgm/18.gif') as number,
    19: require('@bgm/19.gif') as number,
    20: require('@bgm/20.gif') as number,
    21: require('@bgm/21.gif') as number,
    22: require('@bgm/22.gif') as number,
    23: require('@bgm/23.gif') as number,
    24: require('@bgm/24.gif') as number,
    25: require('@bgm/25.gif') as number,
    26: require('@bgm/26.gif') as number,
    27: require('@bgm/27.gif') as number,
    28: require('@bgm/28.gif') as number,
    29: require('@bgm/29.gif') as number,
    30: require('@bgm/30.gif') as number,
    31: require('@bgm/31.gif') as number,
    32: require('@bgm/32.gif') as number,
    33: require('@bgm/33.gif') as number,
    34: require('@bgm/34.gif') as number,
    35: require('@bgm/35.gif') as number,
    36: require('@bgm/36.gif') as number,
    37: require('@bgm/37.gif') as number,
    38: require('@bgm/38.gif') as number,
    39: require('@bgm/39.gif') as number,
    40: require('@bgm/40.gif') as number,
    41: require('@bgm/41.gif') as number,
    42: require('@bgm/42.gif') as number,
    43: require('@bgm/43.gif') as number,
    44: require('@bgm/44.gif') as number,
    45: require('@bgm/45.gif') as number,
    46: require('@bgm/46.gif') as number,
    47: require('@bgm/47.gif') as number,
    48: require('@bgm/48.gif') as number,
    49: require('@bgm/49.gif') as number,
    50: require('@bgm/50.gif') as number,
    51: require('@bgm/51.gif') as number,
    52: require('@bgm/52.gif') as number,
    53: require('@bgm/53.gif') as number,
    54: require('@bgm/54.gif') as number,
    55: require('@bgm/55.gif') as number,
    56: require('@bgm/56.gif') as number,
    57: require('@bgm/57.gif') as number,
    58: require('@bgm/58.gif') as number,
    59: require('@bgm/59.gif') as number,
    60: require('@bgm/60.gif') as number,
    61: require('@bgm/61.gif') as number,
    62: require('@bgm/62.gif') as number,
    63: require('@bgm/63.gif') as number,
    64: require('@bgm/64.gif') as number,
    65: require('@bgm/65.gif') as number,
    66: require('@bgm/66.gif') as number,
    67: require('@bgm/67.gif') as number,
    68: require('@bgm/68.gif') as number,
    69: require('@bgm/69.gif') as number,
    70: require('@bgm/70.gif') as number,
    71: require('@bgm/71.gif') as number,
    72: require('@bgm/72.gif') as number,
    73: require('@bgm/73.gif') as number,
    74: require('@bgm/74.gif') as number,
    75: require('@bgm/75.gif') as number,
    76: require('@bgm/76.gif') as number,
    77: require('@bgm/77.gif') as number,
    78: require('@bgm/78.gif') as number,
    79: require('@bgm/79.gif') as number,
    80: require('@bgm/80.gif') as number,
    81: require('@bgm/81.gif') as number,
    82: require('@bgm/82.gif') as number,
    83: require('@bgm/83.gif') as number,
    84: require('@bgm/84.gif') as number,
    85: require('@bgm/85.gif') as number,
    86: require('@bgm/86.gif') as number,
    87: require('@bgm/87.gif') as number,
    88: require('@bgm/88.gif') as number,
    89: require('@bgm/89.gif') as number,
    90: require('@bgm/90.gif') as number,
    91: require('@bgm/91.gif') as number,
    92: require('@bgm/92.gif') as number,
    93: require('@bgm/93.gif') as number,
    94: require('@bgm/94.gif') as number,
    95: require('@bgm/95.gif') as number,
    96: require('@bgm/96.gif') as number,
    97: require('@bgm/97.gif') as number,
    98: require('@bgm/98.gif') as number,
    99: require('@bgm/99.gif') as number,
    100: require('@bgm/100.gif') as number,
    101: require('@bgm/101.gif') as number,
    102: require('@bgm/102.gif') as number
  }
}
