/*
 * @Author: czy0729
 * @Date: 2022-05-11 04:38:44
 * @Last Modified by: czy0729
 * @Last Modified time: 2025-02-14 08:51:36
 */

/** Home */
export default {
  首页: 'Home',
  '首页.跳转': 'Home.to',
  '首页.标签页点击': 'Home.tabsPress',
  '首页.标签页切换': 'Home.tabsChange',
  '首页.显示收藏管理': 'Home.showManageModal',
  '首页.展开或收起条目': 'Home.itemToggleExpand',
  '首页.置顶或取消置顶': 'Home.itemToggleTop',
  '首页.全部展开': 'Home.expandAll',
  '首页.全部关闭': 'Home.closeAll',
  '首页.选择布局': 'Home.selectLayout',
  '首页.格子布局条目选择': 'Home.selectGirdSubject',
  '首页.观看下一章节': 'Home.doWatchedNextEp',
  '首页.更新书籍下一个章节': 'Home.doUpdateNext',
  '首页.管理收藏': 'Home.doUpdateCollection',
  '首页.章节菜单操作': 'Home.doEpsSelect',
  '首页.章节按钮长按': 'Home.doEpsLongPress',
  '首页.搜索源': 'Home.searchEp',
  '首页.再搜索': 'Home.goSearch',
  '首页.导出日程': 'Home.ics',

  人物: 'Mono',
  '人物.跳转': 'Mono.to',
  '人物.右上角菜单': 'Mono.topRightMenu',
  '人物.收藏人物': 'Mono.doCollect',
  '人物.取消收藏人物': 'Mono.doEraseCollect',
  '人物.封面图查看': 'Mono.imageView',
  '人物.启动ICO': 'Mono.ico',
  '人物.翻译内容': 'Mono.doTranslate',
  '人物.更多资料': 'Mono.onMore',

  条目: 'Subject',
  '条目.查看': 'Subject.view',
  '条目.跳转': 'Subject.to',
  '条目.显示收藏管理': 'Subject.showManageModel',
  '条目.章节倒序': 'Subject.toggleReverseEps',
  '条目.吐槽箱倒序': 'Subject.toggleReverseComments',
  '条目.书籍章节输入框改变': 'Subject.changeText',
  '条目.章节菜单操作': 'Subject.doEpsSelect',
  '条目.管理收藏': 'Subject.doUpdateCollection',
  '条目.更新书籍下一个章节': 'Subject.doUpdateNext',
  '条目.更新书籍章节': 'Subject.doUpdateBookEp',
  '条目.输入框更新章节': 'Subject.doUpdateSubjectEp',
  '条目.章节按钮长按': 'Subject.doEpsLongPress',
  '条目.封面图查看': 'Subject.imageView',
  '条目.右上角菜单': 'Subject.topRightMenu',
  '条目.删除收藏': 'Subject.doEraseCollection',
  '条目.搜索源': 'Subject.searchEp',
  '条目.翻译简介': 'Subject.doTranslate',
  '条目.翻译曲目': 'Subject.doDiscTranslate',
  '条目.查看奖杯': 'Subject.toPSNINE',
  '条目.设置章节筛选': 'Subject.updateFilterEps',
  '条目.阅读轻小说': 'Subject.readNoval',
  '条目.阅读漫画': 'Subject.readManga',
  '条目.预览': 'Subject.viewThumbs',
  '条目.游戏截图': 'Subject.viewGameThumbs',
  '条目.筛选分数': 'Subject.filterScores',
  '条目.筛选吐槽状态': 'Subject.filterStatus',
  '条目.复制标题': 'Subject.copyTitle',
  '条目.展开收起功能块': 'Subject.switchBlock',
  '条目.管理目录': 'Subject.manageFolder',
  '条目.自定义放送': 'Subject.onSelectOnAir',
  '条目.重置放送': 'Subject.resetOnAirUser',
  '条目.吐槽倒序': 'Subject.reverseComment',
  '条目.吐槽看当前版本': 'Subject.currentVersion',
  '条目.拼图分享': 'Subject.sharePoster',
  '条目.特别关注': 'Subject.trackComment',
  '条目.取消特别关注': 'Subject.cancelTrackComment',
  '条目.导出日程': 'Subject.ics',
  '条目.屏蔽用户': 'Subject.blockUser',
  '条目.绝交': 'Subject.blockUser',
  '条目.切换标签类型': 'Subject.switchTyperank',
  '条目.跳转位置': 'Subject.scrollTo',
  '条目.聊天': 'Subject.chat',
  '条目.趋势': 'Subject.trend',

  条目详情: 'SubjectInfo',
  '条目详情.跳转': 'SubjectInfo.to',

  章节: 'Episodes',
  '章节.跳转': 'Episodes.to',
  '章节.右上角菜单': 'Episodes.topRightMenu',

  条目目录: 'SubjectCatalogs',
  '条目目录.跳转': 'SubjectCatalogs.to',
  '条目目录.右上角菜单': 'SubjectCatalogs.topRightMenu',

  用户标签: 'Tag',
  '用户标签.跳转': 'Tag.to',
  '用户标签.右上角菜单': 'Tag.topRightMenu',
  '用户标签.排序选择': 'Tag.onOrderSelect',
  '用户标签.年选择': 'Tag.onAirdateSelect',
  '用户标签.月选择': 'Tag.onMonthSelect',
  '用户标签.公共标签': 'Tag.onMeta',
  '用户标签.切换布局': 'Tag.toggleList',

  作品: 'Works',
  '作品.跳转': 'Works.to',
  '作品.右上角菜单': 'Works.topRightMenu',
  '作品.切换布局': 'Works.toggleList',
  '作品.排序选择': 'Works.onOrderSelect',
  '作品.职位选择': 'Works.onFilterSelect',

  角色: 'Voices',
  '角色.跳转': 'Voices.to',
  '角色.右上角菜单': 'Voices.topRightMenu',
  '角色.职位选择': 'Voices.onFilterSelect',

  更多角色: 'Characters',
  '更多角色.跳转': 'Characters.to',
  '更多角色.右上角菜单': 'Characters.topRightMenu',

  制作人员: 'Persons',
  '制作人员.跳转': 'Persons.to',
  '制作人员.右上角菜单': 'Persons.topRightMenu',

  用户评分: 'Rating',
  '用户评分.跳转': 'Rating.to',
  '用户评分.标签页切换': 'Rating.tabsChange',
  '用户评分.切换类型': 'Rating.toggleFilter',
  '用户评分.右上角菜单': 'Rating.topRightMenu',

  修订历史: 'SubjectWiki',
  '修订历史.右上角菜单': 'SubjectWiki.topRightMenu',

  分类排行: 'Typerank',
  '分类排行.跳转': 'Typerank.to',

  照片墙: 'Overview',
  '照片墙.跳转': 'Overview.to'
}
