/*
 * @Author: czy0729
 * @Date: 2022-08-12 11:47:52
 * @Last Modified by: czy0729
 * @Last Modified time: 2024-01-14 16:43:19
 */
import { rc } from '@utils/dev'
import { COMPONENT as PARENT } from '../ds'

export const COMPONENT_PROVIDER = rc(PARENT, 'KatakanaProvider')

export const COMPONENT = rc(PARENT, 'Katakana')

export const NAMESPACE = 'ComponentKatakana'

export const CACHE_KEY = `${NAMESPACE}|cache`

export const CACHES = {
  'アスキー・メディアワークス': 'ASCII media works',
  'インフィニット・デンドログラム': 'Infinity dendrogram',
  'イン・ザ・ウッズ': 'In the woods',
  'エイ・ワン・シー': 'A-One sea',
  'オルタンシア・サーガ': 'Orlanda Saga',
  'ザ・サード': 'The third',
  'ザ・ファントムストライカーズ': 'The phantom strikers',
  'シン・エヴァンゲリオン': 'Sin Evangelion',
  'ジャンヌ・ダルク': 'Jean nu',
  'ストライク・ザ・ブラッド': 'Strike the blood',
  'ソニー・ミュージックソリューションズ': 'Sony Music solutions',
  'ソードアート・オンライン': 'Art sword Online',
  'ダンス・ダンス・ダンスール': 'Dance dance dance',
  'ダーリン・イン・ザ・フランキス': 'Darling in the Frances',
  'ツバサ・クロニクル': 'Chronicle of',
  'ツユチル・レター': 'Walnut letter',
  'デート・ア・ライブ': 'Date a live',
  'ヒーラー・ガール': 'Healer girl',
  'プレシャス・フレンズ': 'Amazon.co.jp: precious friends',
  'ヘンタイ・プリズン': 'Hentai priest',
  'ホロウ・リアリゼーション': 'Hollowing out',
  'ミア・テイラー': 'Mia Taylor',
  'メリー・ジェーン': 'Mary Jane',
  'リコリス・リコイル': 'Licorice Ricoh',
  'ワンダーエッグ・プライオリティ': 'Bing Web: Wonder egg priority',
  'ヴォルケーノ・トライアングル': 'Vorkano triangle',
  アイキャッチ: 'Catch eye',
  アイドル: 'Idol',
  アオアシ: 'Blue oak',
  アキカン: 'Akkan',
  アクア: 'Aqua',
  アサ: 'ASA',
  アサウラ: 'Asura',
  アサルトリリィ: 'Assault Lily',
  アザトメイキング: 'Azatome King',
  アスリード: 'Ass lead',
  アッパレ: 'Appere',
  アップドリーム: 'Dream up',
  アテンド: 'Athens',
  アニバーサリー: 'Anniversary special',
  アニプレックス: 'Aniplex',
  アニメ: 'Animated cartoon',
  アニメーション: 'Animation',
  アニメーター: 'Animator',
  アライズ: 'Agitation',
  アリア: 'Aria',
  アリオラジャパン: 'ARARIO rajapan',
  アリシゼーション: 'Arisification',
  アリス: 'Alice',
  アルゴナビス: 'Argo Navi',
  アルスノトリア: 'ARS novia',
  アルセウス: 'Arceus',
  アルバム: 'Album',
  アンサンブルコンテスト: 'Ensemble contest',
  イノセンス: 'Innocence',
  イメージ: 'Image',
  インスパイアード: 'Engineered',
  インセクトランド: 'Inct Landes',
  インフィニット: 'Infinity knit',
  イーラ: 'Eira',
  ウソ: 'Lie',
  ウマ: 'A horse',
  ウラオモテ: 'Uranote',
  ウルトラロマンティック: "B'z ultra romantic",
  ウンディーネ: 'Undine',
  エイティシックス: 'Anti six',
  エイル: 'Air',
  エスタブライフ: 'Life tab',
  エッチ: 'Etch',
  エディション: 'Edition',
  エピックレコードジャパン: 'Epic records Japan',
  エマ: 'Emma',
  エモン: 'Emon',
  エロマンガ: 'M - Requiem',
  エロマンガフェスティバル: 'Edgar Festival',
  エンディングテーマ: 'Ending Theme',
  エヴァンゲリオン: 'Evangelion',
  オカルト: 'Occult',
  オギノサトシ: 'Ogino Sato',
  オタケベ: 'Octopus',
  オッドタクシー: 'An odd taxi',
  オトナ: 'Otana',
  オブ: 'Of',
  オリエント: 'Orient',
  オリジナルサウンドトラック: 'CD TV Soundtrack',
  オルタネイティヴ: 'Alternative',
  オーバーラップ: 'Overlaps',
  オーバーロード: 'Overload',
  オープニングテーマ: 'Opening theme',
  オーボエ: 'Oboe',
  カウボーイビバップ: 'Cowboy Bebop',
  カウントダウン: 'Countdown Japan',
  カガステル: 'Casa stone',
  カゴ: 'Basket',
  カスカベ: 'Cascae',
  カッコウ: 'Cuckoo',
  カップル: 'Couple',
  カド: 'Kado',
  カドカワ: 'Cuttlefish',
  カノ: 'Cano',
  カノジョ: 'Canojo',
  カミヤヒサヤス: 'Kamiya hisaya',
  カン: 'Can',
  カンケイ: 'Kankei',
  カンピオーネ: 'Campione',
  カードファイト: 'Card fight',
  ガマン: 'Guman',
  ガンダム: 'Gundam',
  ガンダムビルドダイバーズ: 'Gundam build divers',
  ガーリッシュ: 'Garnish in',
  ガールズ: 'Girls',
  キヌ: 'Kinu',
  キミ: 'Kimi',
  キャッスルヴァニア: 'Castle banyan',
  キャップ: 'Cap',
  キャラ: 'Character',
  キャラソン: 'Carson song',
  キャン: 'Can',
  キングスレイド: 'King Slade',
  キングダム: 'Kingdom',
  ギャングスタ: 'Gangster in',
  ギルティングカムイ: 'Gilling Kamui',
  ギルド: 'Guild',
  クエスチョン: 'Question question',
  クズ: 'Kuzu',
  クラウディア: 'Claudia',
  クラフトソード: 'Craft Sword',
  クレヨン: 'Crayon',
  クール: 'Cool',
  グラフィックデザイン: 'Graphic design',
  グリムガル: 'Glimgal',
  グレイトエスケープ: 'Great escape',
  ケグルイ: 'Kettle',
  ケフィン: 'Kefen',
  ゲー: 'Gate',
  ゲーム: 'Game',
  ココロコネクト: 'Kokoro connect',
  コスプレデビュー: 'Cosplay debut',
  コタロー: 'Kotaro',
  コナン: 'Conan',
  コミック: 'Comic',
  コミックウォーカー: 'Comic Walker',
  コミックガンマ: 'Comic gamma',
  コミックビーズログ: 'Comic be',
  コミュ: 'Community',
  コヤマシゲト: 'Koyama shigeto',
  コン: 'Con',
  コータ: 'Cotter',
  コーチン: 'Cochin',
  ゴンドラ: 'Gondola in',
  ゴーラッシュ: 'Go rush',
  サイコパス: 'Psycho pass',
  サガテレビ: 'Sagami TV',
  サクナヒメ: 'Sakanahime',
  サクラ: 'Sakura',
  サクラクエスト: 'Sakura Quest',
  サクラダリセット: 'Cherry soda reset',
  サマーウォーズ: 'Keywords: summer wars',
  サマータイムレンダ: 'Daylight saving time',
  サマーレッスン: 'Keywords: Summer lesson',
  サモンナイト: 'Knight salmon',
  サル: 'Monkey',
  サンジゲン: 'San Gen',
  サンテレビ: 'Sun TV',
  サンライズ: 'Sunrise',
  サンライズミュージック: 'Music station',
  シグルドリーヴァ: 'Seggleva',
  シャインポスト: 'Main shine post',
  シャドウバース: 'Keywords: Shadow burst',
  シャドーハウス: 'Bing: Shadow house',
  シュート: 'Shoot',
  ショートショート: 'Short short',
  シリーズ: 'Series',
  シワ: 'Wrinkles',
  シングル: 'Single',
  シークレット: 'Schrett',
  シーズン: 'Season',
  ジェンコ: 'Jenko',
  ジャ: 'Jake',
  ジャンプ: 'Jump',
  ジョジョ: 'JOJO',
  ジョー: 'Joe',
  スカウト: 'Scout',
  スクランブル: 'Scramble',
  スクールアイドル: 'Idol school',
  スケルツォ: 'Scherzo',
  スタァライト: 'Light',
  スタジオ: 'Studio',
  スタジオマウス: 'Mouse studio',
  スターリッシュツアーズ: 'Bing Web: Star Tours',
  ステラ: 'Stella',
  ストーンオーシャン: 'Bing: Stone Ocean',
  スナオ: 'SOUNO',
  スプリガン: 'Split gun',
  スペシャル: 'Special',
  スマートフォン: 'Smart phone',
  スライム: 'Slime',
  スラムダンク: 'Keywords: slam dunk',
  スレイブ: 'Slave',
  スローライフ: 'Life slow',
  スーパースター: 'Adidas super star',
  スーパーロボット: 'Keywords: Super robots',
  セツナ: 'Cetna',
  セブンデイズルーム: 'Days seven',
  セブンナイツ: 'Knights seven',
  セーラー: 'Sailor',
  セーラームーン: 'MOON SAILOR',
  ゼノブレイド: 'Genius snow',
  ゼロ: 'Zero',
  ソニー: 'Sony',
  ソング: 'Song',
  ソード: 'Sword',
  ゾロリ: 'Zooris',
  タイムマシンブルース: 'Keywords: Time Machine Blues',
  タツキ: 'Tatsuki',
  タナカ: 'Tanaka',
  タナトスレポート: 'Thanatos Report',
  タムラコータロー: 'Kotaro taro',
  ダックスプロダクション: 'Dachshund production',
  ダメスキル: 'Dame skill',
  ダンジョン: 'Dungeon',
  ダークネス: 'Dark ness',
  チェンソーマン: 'Chainsaw man',
  チャンネル: 'Channel',
  チョッパー: 'Chopper',
  チーズ: 'Cheese',
  チート: 'Cheat',
  チートサバイバル: 'Cheat survival',
  ツギハギ: 'Jungle fish',
  ツバキ: 'Camellia',
  ツルネ: 'Crane',
  ツンデレ: 'Tundene',
  テイルズ: 'Tales',
  テニス: 'Tennis',
  テレ: 'Tele',
  テレビ: 'TV',
  テレビアニメーション: 'Japanese TV animation',
  テーマ: 'Theme',
  ディフィニティブ: 'Defensive in',
  ディレクター: 'Director',
  デカダンス: 'Decadence dance',
  デカルチャー: 'De Culture',
  デキ: 'Deki',
  デザイン: 'Design',
  デザインリーダー: 'Design Leader',
  デザインワークス: 'Design works',
  デジモンアドベンチャー: 'Digimon Adventure',
  デスマーチ: 'Death march',
  デュエルモンスターズ: 'Duel monsters',
  デュエルリンクス: 'Duel Lynx',
  デリシャスパーティ: 'Delicious party',
  デルファイサウンド: 'Delphi sound',
  デーナ: 'Dana',
  トニカクカワイイ: 'Toni kakaiwa',
  トモセシュンサク: 'Tomose shunso',
  トモダチゲーム: 'Tomoda game',
  トラブル: 'Trouble',
  トンネル: 'Tunnel',
  ドキドキ: 'Dogwood',
  ドッカ: 'Dokka',
  ドラ: 'Drum',
  ドラゴン: 'Dragon',
  ドロップキック: 'Drop kick',
  ナイフ: 'Knife',
  ナウシカ: 'Naka deer',
  ナナ: 'Nana',
  ナルト: 'Naruto',
  ナンバー: 'Number',
  ニコニコ: 'Nikko',
  ニッポン: 'Nippon',
  ニューシングル: 'Brand new single',
  ネバーランド: '@ Neverland',
  ネルケプランニング: 'Nerquet planning',
  ノクターン: 'Chopin Nocturne',
  ハイ: 'High',
  ハウス: 'House',
  ハコヅメ: 'Japanese cockroach',
  ハナビ: 'Honeycomb',
  ハルヒ: 'Halhi',
  ハーモニー: 'Harmony',
  ハーレム: 'Harem',
  ハーレムライフ: 'Harem life',
  バカ: 'Idiot',
  バトル: 'Battle',
  バハムート: 'Bahamut',
  バブル: 'Bubble',
  バンダイナムコエンターテインメント: 'Bandai Namco Entertainment',
  バンダイビジュアル: 'Bandai visual',
  バンダーブック: 'Bander book',
  パトレイバー: 'Patrol',
  パニック: 'Panic',
  パブロ: 'Pablo',
  パラディン: 'Paladin',
  パラレルパラダイス: 'Parallel paradise',
  パリピ: 'Palipi',
  パーティー: 'Party',
  ヒカル: 'Hikaru',
  ヒグチアイ: 'Higuchi eye',
  ヒメゴト: 'Meadow',
  ヒロイン: 'Heroine',
  ヒーラー: 'Healer',
  ビシバシ: 'Biglobe',
  ビートフロッグ: 'Beat frog',
  ピングドラム: 'Drum',
  ピンポン: 'Ping Pong',
  ファイアパンチ: 'Fire punch',
  ファイアーエムブレム: 'Fire Emblem',
  ファイブディーズ: 'Five dices',
  ファイル: 'File',
  ファンファーレ: 'Fanfare in',
  フランス: 'France',
  フリーレン: 'Free license',
  フレッシュプリキュア: 'Fresh pretty cure',
  フロップス: 'Flops',
  フロム: 'From me',
  フーゾク: 'Fuzoku',
  ブシロード: 'Busi Road',
  ブシロードミュージック: 'Bushi Road Music',
  ブタ: 'Pig',
  ブッチギレ: 'Butch gilet',
  ブラック: 'Black',
  ブラックカンパニー: 'Black company',
  プランダラ: 'Planadara',
  プリキュア: 'Pretty cure',
  プリティーダービー: 'Bing: pretty Derby',
  プリマドール: 'Primadol',
  プリンス: 'Prince Prince',
  プリンセス: 'Princess',
  プリンセスコネクト: 'Bing: Princess connect',
  プログレッシブ: 'Progressive',
  プロダクション: 'Production',
  プロダクションマネージャー: 'Production manager',
  プロデューサー: 'Producer',
  ペルソナ: 'Persona',
  ボタン: 'Button',
  ボトルマン: 'Bottle man',
  ポケットモンスター: 'Monster pocket',
  ポニーキャニオン: 'Canyon pony',
  マアア: 'Maia',
  マギアレコード: 'Magi allcode',
  マギカ: 'Magica',
  マサト: 'Masato',
  マジ: 'Mage',
  マジカルハート: 'Magical heart',
  マジックカプセル: 'Magic capsule',
  マブラヴ: 'MAV V',
  ママ: 'Mama',
  ママホリック: 'Mama holic',
  マーメイド: 'Mermaid Medley',
  マーヴィージャック: 'Marvy jack',
  ミクスチャー: 'Mixture',
  ミスター: 'Mister',
  ミュウミュウ: 'Mou mule',
  ミュージック: 'Music',
  ムサシ: 'Mackerel',
  メイド: 'Maid',
  メイドインアビス: 'Maid in',
  メガトン: 'Megaton',
  メスガキ: 'Megasaki',
  メディアハウス: 'Media house',
  メディアバンク: 'Media bank',
  メトロイドフュージョン: 'Metroid fusion',
  メロス: 'Melos',
  モテ: 'Mote',
  モトキ: 'Moki',
  モニターワークス: 'Monitor works',
  モブ: 'Mob',
  モーションコミック: 'Motion comics',
  モード: 'Mode',
  モーレツ: 'Morets',
  ヤツ: 'Yats',
  ユアソング: 'Keywords: song song',
  ユリシーズ: 'Ulysses',
  ユーフォニアム: 'Euphonium Hotel',
  ユーレイデコ: 'Eiley Deco',
  ライオン: 'Lion',
  ライデンフィルム: 'Leiden film',
  ライフ: 'Life',
  ラストギアス: 'Last gear',
  ラストダンジョン: 'Last Dungeon',
  ラブオールプレー: 'Love all play',
  ラブコメ: 'Love rice',
  ラブライブ: 'Love letter',
  ラルケ: 'Larke',
  ランチ: 'Lunch',
  ランティス: 'Lampe',
  リアデイル: 'Leah dill',
  リアルエロゲシチュエーション: 'Etiquetas: real EROGE situation',
  リコイル: 'Ricoh',
  リコリス: 'Licorice',
  リダイヤル: 'Dial',
  リマスター: 'Master Remaster',
  リメイク: 'Remake',
  リョウ: 'Leo',
  リラックマ: 'Lilac',
  リリカル: 'Lyrical',
  リーゼロッテ: 'Lease Lotte',
  ルミナスウィッチーズ: 'Lumina sweets',
  ルミヲ: 'Rumi',
  レコンギスタ: 'Leongista',
  レッドデビル: 'Devil Devil',
  レビュアーズ: 'Levers',
  レフティ: 'Lefty',
  レベル: 'Level',
  レボリューション: 'Dance Revolution',
  レヴュースタァライト: 'Review stand light',
  ロックシューター: 'Black Rock Shooter',
  ローリング: 'Rolling',
  ワニ: 'Crocodile',
  ワールド: 'World',
  ヲーターメイド: 'Maid maid',
  ヴァルキュリア: 'Valularia',
  ヴァンガード: 'Van guard',
  ヴェルメイユ: 'Vermeil'
}
